### ISSUE TITLE
mac osx high sierra install issue

### ISSUE THREAD

**Issue by HEMPERORJZS** [Crypto-Currency/Emerald#2]
Process:               Emerald-Qt [24022]
Path:                  /Volumes/VOLUME/Emerald-Qt.app/Contents/MacOS/Emerald-Qt
Identifier:            org.emerald.Emerald-Qt
Version:               $VERSION ($VERSION)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Emerald-Qt [24022]
User ID:               501

Date/Time:             2018-02-03 12:19:27.959 -0600
OS Version:            Mac OS X 10.13.3 (17D47)
Report Version:        12
Anonymous UUID:        6F91CEDF-BF4B-A93E-4A65-9FCB21A20C66

Time Awake Since Boot: 53000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libboost_chrono-mt.dylib
  Referenced from: /Volumes/VOLUME/Emerald-Qt.app/Contents/MacOS/Emerald-Qt
  Reason: image not found

Binary Images:
       0x108aa9000 -        0x10909effb +org.emerald.Emerald-Qt ($VERSION - $VERSION) <314D8D5B-CE55-3180-AA7B-BD954C7ACBB4> /Volumes/VOLUME/Emerald-Qt.app/Contents/MacOS/Emerald-Qt
       0x109226000 -        0x10926dfff +libssl.1.0.0.dylib (0) <23FCCCD7-644F-3620-BA47-6B0F1A42C818> /Volumes/VOLUME/Emerald-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x10928a000 -        0x10940f877 +libcrypto.1.0.0.dylib (0) <196225AA-EE6C-3E28-96ED-5F862CE12E85> /Volumes/VOLUME/Emerald-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x109486000 -        0x10959bff7 +libdb_cxx-4.8.dylib (0) <55936276-8F8D-3D4D-9D82-08548FA316AB> /Volumes/VOLUME/Emerald-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x1095c8000 -        0x1095cafff +libboost_system-mt.dylib (0) <ED86ABC8-84C1-3508-9362-6E2AB9295F0D> /Volumes/VOLUME/Emerald-Qt.app/Contents/Frameworks/libboost_system-mt.dylib
       0x1095d0000 -        0x1095deff7 +libboost_filesystem-mt.dylib (0) <85C65F2C-FCB4-38F0-9CD4-431BF243B211> /Volumes/VOLUME/Emerald-Qt.app/Contents/Frameworks/libboost_filesystem-mt.dylib
       0x1095f2000 -        0x109626fff +libboost_program_options-mt.dylib (0) <2E935CBA-E26F-3563-82DD-55B36E9A5A9A> /Volumes/VOLUME/Emerald-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x109685000 -        0x109691ff7 +libboost_thread-mt.dylib (0) <A6B93F03-1583-326B-A986-DAC5A729045A> /Volumes/VOLUME/Emerald-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x10ec15000 -        0x10ec5f98f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
    0x7fff51350000 -     0x7fff521adfff  com.apple.AppKit (6.9 - 1561.20.106) <D03AE413-C601-3B7C-A3D4-FC32F4C13940> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff521ff000 -     0x7fff521fffff  com.apple.ApplicationServices (48 - 50) <7627DBD6-497B-3AB7-9B63-F0532EDF09B8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff54eaf000 -     0x7fff54eaffff  com.apple.CoreServices (822.19 - 822.19) <44456ED2-59E4-34CB-B41B-C6A82B269949> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff55e85000 -     0x7fff5624afff  com.apple.Foundation (6.9 - 1451) <B99F94E7-117E-39CC-A65D-B7AEA8998481> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation

**Comment by Spidersbox** [comment]
yes. my macOS vm broke, and I haven't had time to re-create it yet.
I was unable to link some of the libs in the img.

**Comment by HEMPERORJZS** [comment]
thank you for a timely response. it is greatly appreciated. looking forward for more to come from this coin and the rest of the jewels.

**Comment by Spidersbox** [comment]
we will post a new macOS wallet when we can get one compiled correctly.
for news and updates, join or Discord: https://discord.gg/gWZQVmE
